"""add schema, schema_timestamp to websites

Revision ID: 2188b4ba9c9c
Revises: dbfd2f7682d2
Create Date: 2025-05-30 11:37:54.145130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2188b4ba9c9c'
down_revision: Union[str, None] = 'dbfd2f7682d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websites', sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('websites', sa.Column('schema_timestamp', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('websites', 'schema_timestamp')
    op.drop_column('websites', 'schema')
    # ### end Alembic commands ###
