"""add search_patter  to websites

Revision ID: 40178ae75cfa
Revises: 769b4cf7d5bd
Create Date: 2025-06-28 12:08:06.931018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40178ae75cfa'
down_revision: Union[str, None] = '769b4cf7d5bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websites', sa.Column('search_pattern', sa.String(), nullable=True))
    op.drop_column('websites', 'particular_search_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websites', sa.Column('particular_search_path', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('websites', 'search_pattern')
    # ### end Alembic commands ###
