"""add particular_search_path and schema_type  to websites

Revision ID: 769b4cf7d5bd
Revises: 2188b4ba9c9c
Create Date: 2025-06-04 21:28:03.921764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '769b4cf7d5bd'
down_revision: Union[str, None] = '2188b4ba9c9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websites', sa.Column('particular_search_path', sa.Boolean(), nullable=True))
    op.add_column('websites', sa.Column('schema_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('websites', 'schema_type')
    op.drop_column('websites', 'particular_search_path')
    # ### end Alembic commands ###
