"""add offer_name  to price offers

Revision ID: 8e91c3c23706
Revises: 40178ae75cfa
Create Date: 2025-06-28 17:08:44.878768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e91c3c23706'
down_revision: Union[str, None] = '40178ae75cfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_prices', sa.Column('offer_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_prices', 'offer_name')
    # ### end Alembic commands ###
