"""add variation_name and variation_key to product_variations

Revision ID: 9eadca2a7fa7
Revises: e9d03948943d
Create Date: 2025-05-28 15:25:52.755629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9eadca2a7fa7'
down_revision: Union[str, None] = 'e9d03948943d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variations', sa.Column('variation_name', sa.String(), nullable=True))
    op.add_column('product_variations', sa.Column('variation_key', sa.String(), nullable=True))
    op.drop_column('product_variations', 'specs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variations', sa.Column('specs', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('product_variations', 'variation_key')
    op.drop_column('product_variations', 'variation_name')
    # ### end Alembic commands ###
