"""add affiliate_link, affiliate_id to websites

Revision ID: dbfd2f7682d2
Revises: 9eadca2a7fa7
Create Date: 2025-05-28 21:59:22.646103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbfd2f7682d2'
down_revision: Union[str, None] = '9eadca2a7fa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websites', sa.Column('affiliate_link', sa.String(), nullable=True))
    op.add_column('websites', sa.Column('affiliate_id', sa.String(), nullable=True))
    op.drop_column('websites', 'sitemap_products_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websites', sa.Column('sitemap_products_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('websites', 'affiliate_id')
    op.drop_column('websites', 'affiliate_link')
    # ### end Alembic commands ###
