"""Add product_variations and website_categories-v2

Revision ID: e9d03948943d
Revises: ba233ba70892
Create Date: 2025-05-26 14:29:28.218825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9d03948943d'
down_revision: Union[str, None] = 'ba233ba70892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_variations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('specs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_variations_id'), 'product_variations', ['id'], unique=False)
    op.create_index(op.f('ix_product_variations_sku'), 'product_variations', ['sku'], unique=False)
    op.add_column('product_prices', sa.Column('variation_id', sa.UUID(), nullable=False))
    op.add_column('product_prices', sa.Column('in_stock', sa.String(), nullable=True))
    op.add_column('product_prices', sa.Column('shipping_cost', sa.Float(), nullable=True))
    op.add_column('product_prices', sa.Column('offer_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('product_prices', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint('product_prices_product_id_fkey', 'product_prices', type_='foreignkey')
    op.create_foreign_key(None, 'product_prices', 'product_variations', ['variation_id'], ['id'])
    op.drop_column('product_prices', 'product_id')
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('ix_products_product_group_id', table_name='products')
    op.drop_index('ix_products_sku', table_name='products')
    op.drop_column('products', 'sku')
    op.drop_column('products', 'product_group_id')
    op.drop_column('products', 'attributes')
    op.add_column('websites', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('websites', sa.Column('sitemap_products_url', sa.String(), nullable=True))
    op.add_column('websites', sa.Column('search_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('websites', 'search_url')
    op.drop_column('websites', 'sitemap_products_url')
    op.drop_column('websites', 'logo_url')
    op.add_column('products', sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('product_group_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('sku', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_products_sku', 'products', ['sku'], unique=True)
    op.create_index('ix_products_product_group_id', 'products', ['product_group_id'], unique=False)
    op.alter_column('products', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.add_column('product_prices', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product_prices', type_='foreignkey')
    op.create_foreign_key('product_prices_product_id_fkey', 'product_prices', 'products', ['product_id'], ['id'])
    op.alter_column('product_prices', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('product_prices', 'offer_metadata')
    op.drop_column('product_prices', 'shipping_cost')
    op.drop_column('product_prices', 'in_stock')
    op.drop_column('product_prices', 'variation_id')
    op.drop_index(op.f('ix_product_variations_sku'), table_name='product_variations')
    op.drop_index(op.f('ix_product_variations_id'), table_name='product_variations')
    op.drop_table('product_variations')
    # ### end Alembic commands ###
