"""add product_group_id to product

Revision ID: eca2e54cbe0a
Revises: bda2cac17766
Create Date: 2025-05-07 21:07:38.852811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca2e54cbe0a'
down_revision: Union[str, None] = 'bda2cac17766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_group_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_products_product_group_id'), 'products', ['product_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_product_group_id'), table_name='products')
    op.drop_column('products', 'product_group_id')
    # ### end Alembic commands ###
